# Generated by Django 2.0.3 on 2018-03-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20180309_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subirdatos',
            name='author',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='describeFunction',
            new_name='describe_function',
        ),
        migrations.DeleteModel(
            name='subirDatos',
        ),
    ]
